# ─────────────────────────────────────────────────────────────
# PredictiveMaintenance IoT • Helm values
# Override any key with: -f my_values.yaml
# ─────────────────────────────────────────────────────────────

replicaCount: 2

image:
  repository: ghcr.io/trojan3877/predmaint
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

env:
  KAFKA_BROKER: "kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  LOG_LEVEL: "Information"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
