apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "predmaint.fullname" . }}
  labels:
    {{- include "predmaint.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "predmaint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "predmaint.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: predmaint
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
